# Form implementation generated from reading ui file 'video1.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets, QtMultimediaWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(616, 701)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fileGroupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.fileGroupBox.setObjectName("fileGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fileGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=self.fileGroupBox)
        self.titleLabel.setStyleSheet("font-size: 16pt; font-weight: bold; margin: 10px;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout.addWidget(self.titleLabel)
        self.filePathEdit = QtWidgets.QLineEdit(parent=self.fileGroupBox)
        self.filePathEdit.setReadOnly(True)
        self.filePathEdit.setObjectName("filePathEdit")
        self.horizontalLayout.addWidget(self.filePathEdit)
        self.selectFileButton = QtWidgets.QPushButton(parent=self.fileGroupBox)
        self.selectFileButton.setObjectName("selectFileButton")
        self.horizontalLayout.addWidget(self.selectFileButton)
        self.verticalLayout.addWidget(self.fileGroupBox)
        self.infoLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.infoLabel.setStyleSheet("color: gray; font-style: italic;")
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.infoLabel)
        self.settingsGroupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.settingsGroupBox.setObjectName("settingsGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.settingsGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.PorogSlider = QtWidgets.QSlider(parent=self.settingsGroupBox)
        self.PorogSlider.setMinimum(1)
        self.PorogSlider.setMaximum(255)
        self.PorogSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.PorogSlider.setObjectName("PorogSlider")
        self.gridLayout.addWidget(self.PorogSlider, 0, 1, 1, 1)
        self.PorogSladerLabel = QtWidgets.QLabel(parent=self.settingsGroupBox)
        self.PorogSladerLabel.setObjectName("PorogSladerLabel")
        self.gridLayout.addWidget(self.PorogSladerLabel, 0, 0, 1, 1)
        self.FilterSizeSlider = QtWidgets.QSlider(parent=self.settingsGroupBox)
        self.FilterSizeSlider.setMinimum(1)
        self.FilterSizeSlider.setMaximum(25)
        self.FilterSizeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.FilterSizeSlider.setObjectName("FilterSizeSlider")
        self.gridLayout.addWidget(self.FilterSizeSlider, 1, 1, 1, 1)
        self.FilterSizeSliderLabel = QtWidgets.QLabel(parent=self.settingsGroupBox)
        self.FilterSizeSliderLabel.setObjectName("FilterSizeSliderLabel")
        self.gridLayout.addWidget(self.FilterSizeSliderLabel, 1, 0, 1, 1)
        self.FilterSizeSliderValue = QtWidgets.QLabel(parent=self.settingsGroupBox)
        self.FilterSizeSliderValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.FilterSizeSliderValue.setObjectName("FilterSizeSliderValue")
        self.gridLayout.addWidget(self.FilterSizeSliderValue, 1, 2, 1, 1)
        self.PorogSliderValue = QtWidgets.QLabel(parent=self.settingsGroupBox)
        self.PorogSliderValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.PorogSliderValue.setObjectName("PorogSliderValue")
        self.gridLayout.addWidget(self.PorogSliderValue, 0, 2, 1, 1)

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.medianButton = QtWidgets.QPushButton(parent=self.settingsGroupBox)
        self.medianButton.setObjectName("medianButton")
        self.medianButton.setCheckable(True)
        self.horizontalLayout_4.addWidget(self.medianButton)
        self.GaussianButton = QtWidgets.QPushButton(parent=self.settingsGroupBox)
        self.GaussianButton.setObjectName("GaussianButton")
        self.GaussianButton.setCheckable(True)
        self.horizontalLayout_4.addWidget(self.GaussianButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 3)

        self.verticalLayout.addWidget(self.settingsGroupBox)
        self.controlsGroupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.controlsGroupBox.setObjectName("controlsGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.controlsGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PredSPom = QtWidgets.QPushButton(parent=self.controlsGroupBox)
        self.PredSPom.setObjectName("PredSPom")
        self.horizontalLayout_2.addWidget(self.PredSPom)
        self.processButton = QtWidgets.QPushButton(parent=self.controlsGroupBox)
        self.processButton.setObjectName("processButton")
        self.horizontalLayout_2.addWidget(self.processButton)
        self.previewButton = QtWidgets.QPushButton(parent=self.controlsGroupBox)
        self.previewButton.setObjectName("previewButton")
        self.horizontalLayout_2.addWidget(self.previewButton)
        self.verticalLayout.addWidget(self.controlsGroupBox)

        self.videoGroupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.videoGroupBox.setObjectName("videoGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.videoGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.videoWidget = QtMultimediaWidgets.QVideoWidget(parent=self.videoGroupBox)
        self.videoWidget.setMinimumSize(QtCore.QSize(0, 300))
        self.videoWidget.setStyleSheet("background-color: black;")
        self.videoWidget.setObjectName("videoWidget")
        self.verticalLayout_2.addWidget(self.videoWidget)
        self.verticalLayout.addWidget(self.videoGroupBox)
        self.verticalLayout.addWidget(self.videoGroupBox)


        self.horizontalScrollBar = QtWidgets.QScrollBar(parent=self.videoGroupBox)
        self.horizontalScrollBar.setStyleSheet("QScrollBar:horizontal {\n"
                                               "    border: none;\n"
                                               "    background: rgba(42, 42, 42, 200);\n"
                                               "    height: 8px;\n"
                                               "    margin: 0px;\n"
                                               "    border-radius: 4px;\n"
                                               "}\n"
                                               "\n"
                                               "QScrollBar::handle:horizontal {\n"
                                               "    background: rgba(96, 96, 96, 200);\n"
                                               "    border-radius: 4px;\n"
                                               "    min-width: 30px;\n"
                                               "}\n"
                                               "\n"
                                               "QScrollBar::handle:horizontal:hover {\n"
                                               "    background: rgba(128, 128, 128, 200);\n"
                                               "}\n"
                                               "\n"
                                               "QScrollBar::handle:horizontal:pressed {\n"
                                               "    background: rgba(170, 170, 170, 200);\n"
                                               "}\n"
                                               "\n"
                                               "QScrollBar::sub-line:horizontal, QScrollBar::add-line:horizontal {\n"
                                               "    border: none;\n"
                                               "    background: none;\n"
                                               "    width: 0px;\n"
                                               "    height: 0px;\n"
                                               "}\n"
                                               "\n"
                                               "QScrollBar::sub-page:horizontal, QScrollBar::add-page:horizontal {\n"
                                               "    background: none;\n"
                                               "}")
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.verticalLayout_2.addWidget(self.horizontalScrollBar)
        self.verticalLayout.addWidget(self.videoGroupBox)
        self.statusLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.statusLabel.setStyleSheet("font-weight: bold;")
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.downloadGroupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.downloadGroupBox.setObjectName("downloadGroupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.downloadGroupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.downloadCleanButton = QtWidgets.QPushButton(parent=self.downloadGroupBox)
        self.downloadCleanButton.setObjectName("downloadCleanButton")
        self.horizontalLayout_3.addWidget(self.downloadCleanButton)
        self.CrushButton = QtWidgets.QPushButton(parent=self.downloadGroupBox)
        self.CrushButton.setObjectName("CrushButton")
        self.horizontalLayout_3.addWidget(self.CrushButton)
        self.verticalLayout.addWidget(self.downloadGroupBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Видео обработчик помех"))
        self.fileGroupBox.setTitle(_translate("MainWindow", "Выбор видеофайла"))
        self.titleLabel.setText(_translate("MainWindow", "Обработка видео с помехами"))
        self.selectFileButton.setText(_translate("MainWindow", "Выбрать"))
        self.infoLabel.setText(_translate("MainWindow", "Видео не загружено"))
        self.settingsGroupBox.setTitle(_translate("MainWindow", "Настройки обнаружения помех"))
        self.PorogSladerLabel.setText(_translate("MainWindow", "Порог обнаружения помех:"))
        self.FilterSizeSliderLabel.setText(_translate("MainWindow", "Размер фильтра:"))
        self.FilterSizeSliderValue.setText(_translate("MainWindow", "20"))
        self.PorogSliderValue.setText(_translate("MainWindow", "255"))
        self.medianButton.setText(_translate("MainWindow", "Метод Медианы"))
        self.GaussianButton.setText(_translate("MainWindow", "Метод Гаусса"))
        self.controlsGroupBox.setTitle(_translate("MainWindow", "Управление"))
        self.processButton.setText(_translate("MainWindow", "Обработать видео"))
        self.PredSPom.setText(_translate("MainWindow", "Показать шумные кадры"))
        self.previewButton.setText(_translate("MainWindow", "Показать чистые кадры"))
        self.videoGroupBox.setTitle(_translate("MainWindow", "Визуализация помех"))
        self.statusLabel.setText(_translate("MainWindow", "Готов к работе"))
        self.downloadGroupBox.setTitle(_translate("MainWindow", "Скачивание результатов"))
        self.downloadCleanButton.setText(_translate("MainWindow", "Скачать видео без помех"))
        self.CrushButton.setText(_translate("MainWindow", "Скачать видео с помехами"))